Repository xoofx/markdig, pull requests merged in 2022-04, with the labels that each got.

#607 Start of documentation on parser
  doc/parsing-ast.md
  doc/parsing-extensions.md
  doc/parsing-overview.md
Labels: documentation

#621 April perf improvements
  src/Markdig.Tests/TestLazySubstring.cs
  src/Markdig.Tests/TestMarkdigCoreApi.cs
  src/Markdig/Extensions/AutoLinks/AutoLinkParser.cs
  src/Markdig/Extensions/Bootstrap/BootstrapExtension.cs
  src/Markdig/Helpers/ArrayHelper.cs
  src/Markdig/Helpers/BlockWrapper.cs
  src/Markdig/Helpers/CharHelper.cs
  src/Markdig/Helpers/LazySubstring.cs
  src/Markdig/Markdown.cs
  src/Markdig/MarkdownPipeline.cs
  src/Markdig/Parsers/BlockProcessor.cs
  src/Markdig/Parsers/InlineProcessor.cs
  src/Markdig/Parsers/Inlines/CodeInlineParser.cs
  src/Markdig/Parsers/Inlines/EmphasisInlineParser.cs
  src/Markdig/Parsers/Inlines/LiteralInlineParser.cs
  src/Markdig/Parsers/ListBlockParser.cs
  src/Markdig/Parsers/NumberedListItemParser.cs
  src/Markdig/Renderers/Html/Inlines/CodeInlineRenderer.cs
  src/Markdig/Renderers/Normalize/Inlines/CodeInlineRenderer.cs
  src/Markdig/Renderers/RendererBase.cs
  src/Markdig/Renderers/Roundtrip/Inlines/CodeInlineRenderer.cs
  src/Markdig/Syntax/Block.cs
  src/Markdig/Syntax/ContainerBlock.cs
  src/Markdig/Syntax/Inlines/CodeInline.cs
  src/Markdig/Syntax/Inlines/ContainerInline.cs
  src/Markdig/Syntax/Inlines/DelimiterType.cs
  src/Markdig/Syntax/Inlines/Inline.cs
  src/Markdig/Syntax/Inlines/LinkDelimiterInline.cs
  src/Markdig/Syntax/Inlines/LinkInline.cs
  src/Markdig/Syntax/Inlines/LiteralInline.cs
  src/Markdig/Syntax/MarkdownObject.cs
Labels: enhancement

#622 Vectorize CharacterMap.IndexOfOpeningCharacter
  src/Markdig/Helpers/CharacterMap.cs
Labels: enhancement

#623 Fix GlobalizationExtension RTL detection
  src/Markdig.Tests/Specs/GlobalizationSpecs.generated.cs
  src/Markdig.Tests/Specs/GlobalizationSpecs.md
  src/Markdig/Extensions/Globalization/GlobalizationExtension.cs
Labels: enhancement

#627 Update commonmark spec 0.30
  src/Markdig.Tests/Specs/CommonMark.generated.cs
  src/Markdig.Tests/Specs/CommonMark.md
  src/Markdig/Parsers/HtmlBlockParser.cs
  src/Markdig/Syntax/LinkReferenceDefinitionGroup.cs
Labels: enhancement

#632 Don't try to use the MT pointer on unsupported platforms
  src/Markdig/Renderers/RendererBase.cs
Labels: bug
